# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from UI_Huffman import Ui_UI_Huffman  # 确保导入 Huffman 界面
from UI_Fano import Ui_UI_Fano          #导入Fano界面
from UI_Shannon import  Ui_UI_Shannon   #导入Shannon界面

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 720)
        self.Huffman_Button = QtWidgets.QPushButton(Form)
        self.Huffman_Button.setGeometry(QtCore.QRect(90, 300, 180, 100))
        self.Huffman_Button.setObjectName("Huffman_Button")
        self.Fano_Button = QtWidgets.QPushButton(Form)
        self.Fano_Button.setGeometry(QtCore.QRect(350, 300, 180, 100))
        self.Fano_Button.setObjectName("Fano_Button")
        self.Shannon_Button = QtWidgets.QPushButton(Form)
        self.Shannon_Button.setGeometry(QtCore.QRect(610, 300, 180, 100))
        self.Shannon_Button.setObjectName("Shannon_Button")
        self.TITLE = QtWidgets.QLabel(Form)
        self.TITLE.setGeometry(QtCore.QRect(160, 100, 600, 110))
        self.TITLE.setTextFormat(QtCore.Qt.AutoText)
        self.TITLE.setScaledContents(False)
        self.TITLE.setObjectName("TITLE")
        self.Author = QtWidgets.QLabel(Form)
        self.Author.setGeometry(QtCore.QRect(670, 660, 221, 51))
        self.Author.setObjectName("Author")
        self.Quit = QtWidgets.QPushButton(Form)
        self.Quit.setGeometry(QtCore.QRect(740, 560, 130, 60))
        self.Quit.setObjectName("Quit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #界面切换
        # 按下退出按钮关闭界面
        self.Quit.clicked.connect(QtWidgets.QApplication.quit)
        #点击Huffman_Button显示Huffman界面
        self.Huffman_Button.clicked.connect(self.showHuffman)
        self.Form = Form  # Save the reference to the main form
        #点击Fano_Button显示Fano界面
        self.Fano_Button.clicked.connect(self.showFano)
        self.Form = Form
        # 点击Shannon_Button显示Shannon界面
        self.Shannon_Button.clicked.connect(self.showShannon)
        self.Form = Form

        #显示Huffman界面
    def showHuffman(self):
        self.huffman_window = QtWidgets.QMainWindow()
        self.ui = Ui_UI_Huffman()
        self.ui.setupUi(self.huffman_window)
        self.huffman_window.show()
        self.Form.close()  # Close the main form
    #显示Fano界面
    def showFano(self):
        self.fano_window = QtWidgets.QMainWindow()
        self.ui = Ui_UI_Fano()
        self.ui.setupUi(self.fano_window)
        self.fano_window.show()
        self.Form.close()
    #显示Shannon界面
    def showShannon(self):
        self.shannon_window = QtWidgets.QMainWindow()
        self.ui = Ui_UI_Shannon()
        self.ui.setupUi(self.shannon_window)
        self.shannon_window.show()
        self.Form.close()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "信息论课程设计"))
        self.Huffman_Button.setText(_translate("Form", "点此进入Huffman编码"))
        self.Fano_Button.setText(_translate("Form", "点此进入Fano编码"))
        self.Shannon_Button.setText(_translate("Form", "点此进入Shannon编码"))
        self.TITLE.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">信息论课程设计</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">——霍夫曼、费诺、香农编码(Python语言实现)</span></p></body></html>"))
        self.Author.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Presented by Captain-Rhino</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    <span style=\" color:#0055ff;\">Toss_3@163.com</span></p></body></html>"))
        self.Quit.setText(_translate("Form", "结束程序"))

if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    #import pics_ui_rc # 导入添加的资源（根据实际情况填写文件名）
    app = QApplication(sys.argv)
    Form = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())