# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Huffman.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI_Huffman(object):
    def setupUi(self, UI_Huffman):
        UI_Huffman.setObjectName("UI_Huffman")
        UI_Huffman.resize(900, 720)
        self.TITLE = QtWidgets.QLabel(UI_Huffman)
        self.TITLE.setGeometry(QtCore.QRect(200, 30, 480, 100))
        self.TITLE.setObjectName("TITLE")
        self.Back_to_Start_button = QtWidgets.QPushButton(UI_Huffman)
        self.Back_to_Start_button.setGeometry(QtCore.QRect(740, 550, 150, 90))
        self.Back_to_Start_button.setObjectName("Back_to_Start_button")
        self.Input_Symbol_textedit = QtWidgets.QTextEdit(UI_Huffman)
        self.Input_Symbol_textedit.setGeometry(QtCore.QRect(40, 190, 260, 60))
        self.Input_Symbol_textedit.setObjectName("Input_Symbol_textedit")
        self.Input_Q_hint = QtWidgets.QLabel(UI_Huffman)
        self.Input_Q_hint.setGeometry(QtCore.QRect(50, 130, 220, 50))
        self.Input_Q_hint.setObjectName("Input_Q_hint")
        self.Input_N_textedit = QtWidgets.QTextEdit(UI_Huffman)
        self.Input_N_textedit.setGeometry(QtCore.QRect(360, 190, 100, 61))
        self.Input_N_textedit.setObjectName("Input_N_textedit")
        self.Input_N_hint = QtWidgets.QLabel(UI_Huffman)
        self.Input_N_hint.setGeometry(QtCore.QRect(350, 130, 140, 50))
        self.Input_N_hint.setObjectName("Input_N_hint")
        self.Input_R_textedit = QtWidgets.QTextEdit(UI_Huffman)
        self.Input_R_textedit.setGeometry(QtCore.QRect(610, 190, 100, 61))
        self.Input_R_textedit.setObjectName("Input_R_textedit")
        self.Input_R_hint = QtWidgets.QLabel(UI_Huffman)
        self.Input_R_hint.setGeometry(QtCore.QRect(580, 130, 150, 50))
        self.Input_R_hint.setObjectName("Input_R_hint")
        self.Generate_button = QtWidgets.QPushButton(UI_Huffman)
        self.Generate_button.setGeometry(QtCore.QRect(740, 400, 150, 90))
        self.Generate_button.setObjectName("Generate_button")
        self.Output_textbrowser = QtWidgets.QTextBrowser(UI_Huffman)
        self.Output_textbrowser.setGeometry(QtCore.QRect(40, 310, 671, 381))
        self.Output_textbrowser.setObjectName("Output_textbrowser")
        self.Output_hint = QtWidgets.QLabel(UI_Huffman)
        self.Output_hint.setGeometry(QtCore.QRect(140, 270, 471, 41))
        self.Output_hint.setObjectName("Output_hint")

        self.retranslateUi(UI_Huffman)
        QtCore.QMetaObject.connectSlotsByName(UI_Huffman)

        # 返回按钮点下回到start界面
        self.Back_to_Start_button.clicked.connect(self.backToStart)

    def backToStart(self):
        from start import Ui_Form
        self.start_window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.start_window)
        self.start_window.show()
        QtWidgets.QWidget.close(self.Back_to_Start_button.window())
#1

    def retranslateUi(self, UI_Huffman):
        _translate = QtCore.QCoreApplication.translate
        UI_Huffman.setWindowTitle(_translate("UI_Huffman", "UI_Huffman"))
        self.TITLE.setText(_translate("UI_Huffman", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Huffman编码</span></p><p align=\"center\"><span style=\" font-size:16pt;\">任意Q符号N重序列信源的最优R进制编码</span></p><p><br/></p></body></html>"))
        self.Back_to_Start_button.setText(_translate("UI_Huffman", "返回到初始界面"))
        self.Input_Symbol_textedit.setHtml(_translate("UI_Huffman", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Input_Q_hint.setText(_translate("UI_Huffman", "<html><head/><body><p>在这里输入符号</p><p>注意符号长度:8 &lt;= Q &lt;= 15</p></body></html>"))
        self.Input_N_hint.setText(_translate("UI_Huffman", "<html><head/><body><p>输入N</p><p>注意：1&lt;= N &lt;=3</p></body></html>"))
        self.Input_R_hint.setText(_translate("UI_Huffman", "<html><head/><body><p>输入进制R</p><p>注意：2&lt;= R &lt;=5</p></body></html>"))
        self.Generate_button.setText(_translate("UI_Huffman", "Generate"))
        self.Output_hint.setText(_translate("UI_Huffman", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">运行结果</span></p></body></html>"))


if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    #import pics_ui_rc # 导入添加的资源（根据实际情况填写文件名）
    app = QApplication(sys.argv)
    UI_Huffman = QMainWindow()
    ui = Ui_UI_Huffman()
    ui.setupUi(UI_Huffman)
    UI_Huffman.show()
    sys.exit(app.exec_())